### ISSUE TITLE
Why do you use `Html Never` instead of `Html msg`?

### ISSUE THREAD

**Issue by marubinotto** [pablohirafuji/elm-markdown#1]
Hi,

Thank you for your great work. I've been looking for a library like this.

Why do you use `Html Never` instead of `Html msg` for the API? Because of this, I can't attach events to customized output elements.

**Comment by pablohirafuji** [comment]
Hey,

I did it because I thought that a markdown should never return a message. I made a [post](https://groups.google.com/forum/#!topic/elm-dev/lwov7jRMcS8) on elm-dev asking for feedback, and I will change that in version 2.0.0.

I will expose the AST too, so it will be way more flexible. I rewrote the Inline parser too, should be faster and more reliable.

Should be up in the next few days. Thanks for the feedback!

**Comment by pablohirafuji** [comment]
Released new version http://package.elm-lang.org/packages/pablohirafuji/elm-markdown/latest.
